name: Melon Ticket Actions
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run script
        uses: mooyoul/melon-ticket-actions@master
        with:
          email: ${{ secrets.MELON_ID }}
          password: ${{ secrets.MELON_PW }}
          showlog: true
